var DEMO_FULL = [
'project:',
'  name: "Полная модель компании"',
'  version: 2',
'',
'nodes:',
'  - id: NET_PROFIT',
'    type: TARGET',
'    label: "Чистая прибыль"',
'    source: computed',
'',
'  - id: EBT',
'    type: INTERMEDIATE',
'    label: "Прибыль до налогообложения"',
'    source: computed',
'',
'  - id: TAX',
'    type: INTERMEDIATE',
'    label: "Налог на прибыль"',
'    source: computed',
'',
'  - id: TAX_RATE',
'    type: INPUT',
'    label: "Ставка налога на прибыль"',
'    value: 0.20',
'    min: 0.15',
'    max: 0.25',
'    source: manual',
'    enabled: true',
'',
'  - id: EBITDA',
'    type: INTERMEDIATE',
'    label: "EBITDA"',
'    source: computed',
'',
'  - id: DA',
'    type: INTERMEDIATE',
'    label: "Амортизация"',
'    source: computed',
'',
'  - id: EBIT',
'    type: INTERMEDIATE',
'    label: "Операционная прибыль"',
'    source: computed',
'',
'  - id: INTEREST',
'    type: INTERMEDIATE',
'    label: "Проценты к уплате"',
'    source: computed',
'',
'  - id: INTEREST_INCOME',
'    type: INPUT',
'    label: "Проценты к получению"',
'    value: 0',
'    min: 0',
'    max: 500000,
'    source: manual',
'    enabled: true',
'',
'  - id: OTHER_INCOME',
'    type: INPUT',
'    label: "Прочие доходы"',
'    value: 200000',
'    min: 0',
'    max: 1000000',
'    source: manual',
'    enabled: true',
'',
'  - id: OTHER_EXP',
'    type: INPUT',
'    label: "Прочие расходы"',
'    value: 100000',
'    min: 0',
'    max: 500000',
'    source: manual',
'    enabled: true',
'',
'  - id: PENALTIES',
'    type: INPUT',
'    label: "Штрафы"',
'    value: 0',
'    min: 0',
'    max: 10000000',
'    source: manual',
'    enabled: true',
'',
'  - id: GROSS_PROFIT',
'    type: INTERMEDIATE',
'    label: "Валовая прибыль"',
'    source: computed',
'',
'  - id: REVENUE',
'    type: INTERMEDIATE',
'    label: "Выручка"',
'    source: computed',
'',
'  - id: COGS',
'    type: INTERMEDIATE',
'    label: "Себестоимость"',
'    source: computed',
'',
'  - id: SELLING_EXP',
'    type: INTERMEDIATE',
'    label: "Коммерческие расходы"',
'    source: computed',
'',
'  - id: ADMIN_EXP',
'    type: INTERMEDIATE',
'    label: "Управленческие расходы"',
'    source: computed',
'',
'  - id: PRICE',
'    type: INPUT',
'    label: "Цена"',
'    value: 1200',
'    min: 900',
'    max: 1500',
'    source: manual',
'    enabled: true',
'',
'  - id: VOLUME',
'    type: INPUT',
'    label: "Объём продаж"',
'    value: 8500',
'    min: 1000',
'    max: 50000',
'    source: manual',
'    enabled: true',
'',
'  - id: MARKETING',
'    type: INPUT',
'    label: "Маркетинг"',
'    value: 1200000',
'    min: 500000',
'    max: 5000000',
'    source: manual',
'    enabled: true',
'',
'  - id: SEASON',
'    type: INPUT',
'    label: "Сезонность"',
'    value: 1.0',
'    min: 0.7',
'    max: 1.3',
'    source: manual',
'    enabled: true',
'',
'  - id: BUSINESS_ACTIVITY',
'    type: INTERMEDIATE',
'    label: "Деловая активность"',
'    source: computed',
'',
'  - id: CB_RATE',
'    type: EXTERNAL',
'    label: "Ставка ЦБ"',
'    value: 18.0',
'    min: 5',
'    max: 25',
'    source: manual',
'    enabled: true',
'',
'  - id: PMI',
'    type: EXTERNAL',
'    label: "Индекс PMI"',
'    value: 52.0',
'    min: 40',
'    max: 65',
'    source: manual',
'    enabled: true',
'',
'  - id: CCI',
'    type: EXTERNAL',
'    label: "Потребительская уверенность"',
'    value: -8.0',
'    min: -40',
'    max: 10',
'    source: manual',
'    enabled: true',
'',
'  - id: SANCTIONS',
'    type: EXTERNAL',
'    label: "Санкционный индекс"',
'    value: 0.7',
'    min: 0',
'    max: 1.0',
'    source: manual',
'    enabled: true',
'',
'  - id: COMPETITION',
'    type: INPUT',
'    label: "Конкуренция"',
'    value: 0.8',
'    min: 0.5',
'    max: 1.0',
'    source: manual',
'    enabled: true',
'',
'  - id: HOUSEHOLD_INCOME',
'    type: EXTERNAL',
'    label: "Доходы населения"',
'    value: 55000',
'    min: 30000',
'    max: 80000',
'    source: manual',
'    enabled: true',
'',
'  - id: BASE_MATERIAL_PRICE',
'    type: INPUT',
'    label: "Базовая цена сырья"',
'    value: 520',
'    min: 400',
'    max: 700',
'    source: manual',
'    enabled: true',
'',
'  - id: UNIT_MATERIAL',
'    type: INTERMEDIATE',
'    label: "Цена сырья (скорректированная)"',
'    source: computed',
'',
'  - id: MATERIAL_COST',
'    type: INTERMEDIATE',
'    label: "Материальные затраты"',
'    source: computed',
'',
'  - id: INFLATION',
'    type: EXTERNAL',
'    label: "Инфляция"',
'    value: 7.0',
'    min: 3',
'    max: 20',
'    source: manual',
'    enabled: true',
'',
'  - id: FX_RATE',
'    type: EXTERNAL',
'    label: "Курс валюты"',
'    value: 95.0',
'    min: 70',
'    max: 130',
'    source: manual',
'    enabled: true',
'',
'  - id: TARIFFS',
'    type: EXTERNAL',
'    label: "Тарифы монополий"',
'    value: 1.05',
'    min: 0.9',
'    max: 1.3',
'    source: manual',
'    enabled: true',
'',
'  - id: GEO_INDEX',
'    type: EXTERNAL',
'    label: "Геополитический индекс"',
'    value: 0.7',
'    min: 0',
'    max: 1.0',
'    source: manual',
'    enabled: true',
'',
'  - id: SUPPLIER_RISK',
'    type: EXTERNAL',
'    label: "Риск дефолта поставщика"',
'    value: 0.05',
'    min: 0',
'    max: 1.0',
'    source: manual',
'    enabled: true',
'',
'  - id: DIRECT_LABOR',
'    type: INTERMEDIATE',
'    label: "Оплата труда произв. персонала"',
'    source: computed',
'',
'  - id: PROD_HEADCOUNT',
'    type: INPUT',
'    label: "Численность произв. персонала"',
'    value: 60',
'    min: 40',
'    max: 100',
'    source: manual',
'    enabled: true',
'',
'  - id: PROD_AVG_SALARY',
'    type: INPUT',
'    label: "Средняя ЗП произв. персонала"',
'    value: 58000',
'    min: 40000',
'    max: 80000',
'    source: manual',
'    enabled: true',
'',
'  - id: ENERGY_RATE',
'    type: INPUT',
'    label: "Норма энергозатрат на единицу"',
'    value: 45',
'    min: 30',
'    max: 70',
'    source: manual',
'    enabled: true',
'',
'  - id: ENERGY_COST',
'    type: INTERMEDIATE',
'    label: "Энергозатраты"',
'    source: computed',
'',
'  - id: LOGISTICS_RATE',
'    type: INPUT',
'    label: "Стоимость доставки единицы"',
'    value: 30',
'    min: 15',
'    max: 60',
'    source: manual',
'    enabled: true',
'',
'  - id: LOGISTICS_COST',
'    type: INTERMEDIATE',
'    label: "Логистика"',
'    source: computed',
'',
'  - id: DEFECT_RATE',
'    type: INPUT',
'    label: "Брак"',
'    value: 0.03',
'    min: 0.01',
'    max: 0.10',
'    source: manual',
'    enabled: true',
'',
'  - id: SCALE_EFFECT',
'    type: INTERMEDIATE',
'    label: "Эффект масштаба"',
'    source: computed',
'',
'  - id: ADMIN_PAYROLL',
'    type: INTERMEDIATE',
'    label: "ФОТ АУП"',
'    source: computed',
'',
'  - id: ADMIN_HEADCOUNT',
'    type: INPUT',
'    label: "Численность АУП"',
'    value: 35',
'    min: 20',
'    max: 60',
'    source: manual',
'    enabled: true',
'',
'  - id: ADMIN_AVG_SALARY',
'    type: INPUT',
'    label: "Средняя ЗП АУП"',
'    value: 85000',
'    min: 60000',
'    max: 120000',
'    source: manual',
'    enabled: true',
'',
'  - id: LABOR_INDEX',
'    type: EXTERNAL',
'    label: "Индекс рынка труда"',
'    value: 0.8',
'    min: 0.5',
'    max: 1.5',
'    source: manual',
'    enabled: true',
'',
'  - id: SPI',
'    type: INPUT',
'    label: "Индекс пирамиды зарплат"',
'    value: 4.2',
'    min: 1.0',
'    max: 10.0',
'    source: manual',
'    enabled: true',
'',
'  - id: ATTRITION',
'    type: INTERMEDIATE',
'    label: "Текучесть персонала"',
'    source: computed',
'',
'  - id: ENGAGEMENT',
'    type: INPUT',
'    label: "Вовлечённость персонала"',
'    value: 0.65',
'    min: 0.3',
'    max: 1.0',
'    source: manual',
'    enabled: true',
'',
'  - id: EFFECTIVE_HEADCOUNT',
'    type: INTERMEDIATE',
'    label: "Эффективная численность (с учётом текучести)"',
'    source: computed',
'',
'  - id: RENT',
'    type: INPUT',
'    label: "Аренда"',
'    value: 350000',
'    min: 200000',
'    max: 500000',
'    source: manual',
'    enabled: true',
'',
'  - id: IT_EXP',
'    type: INPUT',
'    label: "IT-расходы"',
'    value: 150000',
'    min: 50000',
'    max: 300000',
'    source: manual',
'    enabled: true',
'',
'  - id: RD_EXP',
'    type: INPUT',
'    label: "R&D расходы"',
'    value: 100000',
'    min: 0',
'    max: 500000',
'    source: manual',
'    enabled: true',
'',
'  - id: TRAINING_EXP',
'    type: INPUT',
'    label: "Обучение персонала"',
'    value: 50000',
'    min: 0',
'    max: 200000',
'    source: manual',
'    enabled: true',
'',
'  - id: FIXED_ASSETS',
'    type: INPUT',
'    label: "Основные средства"',
'    value: 12000000',
'    min: 5000000',
'    max: 30000000',
'    source: manual',
'    enabled: true',
'',
'  - id: INTANGIBLE_ASSETS',
'    type: INPUT',
'    label: "Нематериальные активы"',
'    value: 2000000',
'    min: 0',
'    max: 10000000',
'    source: manual',
'    enabled: true',
'',
'  - id: DA_RATE',
'    type: INPUT',
'    label: "Норма амортизации"',
'    value: 0.10',
'    min: 0.05',
'    max: 0.20',
'    source: manual',
'    enabled: true',
'',
'  - id: WEAR',
'    type: INTERMEDIATE',
'    label: "Износ оборудования"',
'    source: computed',
'',
'  - id: CAPEX',
'    type: INPUT',
'    label: "Капитальные затраты"',
'    value: 800000',
'    min: 0',
'    max: 3000000',
'    source: manual',
'    enabled: true',
'',
'  - id: CAPACITY_UTIL',
'    type: INPUT',
'    label: "Загрузка мощностей"',
'    value: 0.78',
'    min: 0.4',
'    max: 1.0',
'    source: manual',
'    enabled: true',
'',
'  - id: TECH_OBSOLESCENCE',
'    type: INPUT',
'    label: "Технологическое устаревание"',
'    value: 0.05',
'    min: 0',
'    max: 0.15',
'    source: manual',
'    enabled: true',
'',
'  - id: LOANS',
'    type: INPUT',
'    label: "Кредитный портфель"',
'    value: 5000000',
'    min: 0',
'    max: 20000000',
'    source: manual',
'    enabled: true',
'',
'  - id: LOAN_RATE',
'    type: INTERMEDIATE',
'    label: "Ставка по кредитам"',
'    source: computed',
'',
'  - id: BANK_SPREAD',
'    type: INPUT',
'    label: "Спред банка"',
'    value: 0.03',
'    min: 0.01',
'    max: 0.08',
'    source: manual',
'    enabled: true',
'',
'  - id: RATE_TYPE',
'    type: INPUT',
'    label: "Тип ставки"',
'    value: 0',
'    min: 0',
'    max: 1',
'    source: manual',
'    enabled: true',
'',
'  - id: CREDIT_RATING',
'    type: INPUT',
'    label: "Кредитный рейтинг"',
'    value: 0.70',
'    min: 0.2',
'    max: 1.0',
'    source: manual',
'    enabled: true',
'',
'  - id: DEBT_EBITDA',
'    type: INTERMEDIATE',
'    label: "Debt/EBITDA"',
'    source: computed',
'',
'  - id: CASH_START',
'    type: INPUT',
'    label: "Денежные средства на начало периода"',
'    value: 5000000',
'    min: 0',
'    max: 20000000',
'    source: manual',
'    enabled: true',
'',
'  - id: FCF',
'    type: INTERMEDIATE',
'    label: "Свободный денежный поток"',
'    source: computed',
'',
'  - id: CASH',
'    type: INTERMEDIATE',
'    label: "Денежные средства"',
'    source: computed',
'',
'  - id: CFO',
'    type: INTERMEDIATE',
'    label: "Операционный денежный поток"',
'    source: computed',
'',
'  - id: CFI',
'    type: INTERMEDIATE',
'    label: "Инвестиционный денежный поток"',
'    source: computed',
'',
'  - id: CFF',
'    type: INTERMEDIATE',
'    label: "Финансовый денежный поток"',
'    source: computed',
'',
'  - id: delta_RECEIVABLES',
'    type: INPUT',
'    label: "Изменение дебиторской задолженности"',
'    value: 300000',
'    min: -2000000',
'    max: 2000000',
'    source: manual',
'    enabled: true',
'',
'  - id: delta_PAYABLES',
'    type: INPUT',
'    label: "Изменение кредиторской задолженности"',
'    value: 150000',
'    min: -1000000',
'    max: 1000000',
'    source: manual',
'    enabled: true',
'',
'  - id: delta_INVENTORY',
'    type: INPUT',
'    label: "Изменение запасов"',
'    value: 200000',
'    min: -2000000',
'    max: 2000000',
'    source: manual',
'    enabled: true',
'',
'  - id: NEW_LOANS',
'    type: INPUT',
'    label: "Новые кредиты"',
'    value: 0',
'    min: 0',
'    max: 10000000',
'    source: manual',
'    enabled: true',
'',
'  - id: LOAN_REPAYMENT',
'    type: INPUT',
'    label: "Погашение кредитов"',
'    value: 600000',
'    min: 0',
'    max: 5000000',
'    source: manual',
'    enabled: true',
'',
'  - id: DIVIDENDS',
'    type: INPUT',
'    label: "Дивиденды"',
'    value: 0',
'    min: 0',
'    max: 5000000',
'    source: manual',
'    enabled: true',
'',
'  - id: INVENTORY',
'    type: INPUT',
'    label: "Товарные запасы"',
'    value: 3200000',
'    min: 1000000',
'    max: 6000000',
'    source: manual',
'    enabled: true',
'',
'  - id: RECEIVABLES',
'    type: INPUT',
'    label: "Дебиторская задолженность"',
'    value: 2500000',
'    min: 500000',
'    max: 5000000',
'    source: manual',
'    enabled: true',
'',
'  - id: PAYABLES',
'    type: INPUT',
'    label: "Кредиторская задолженность"',
'    value: 1800000',
'    min: 500000',
'    max: 3000000',
'    source: manual',
'    enabled: true',
'',
'  - id: CURRENT_ASSETS',
'    type: INTERMEDIATE',
'    label: "Оборотные активы"',
'    source: computed',
'',
'  - id: ASSETS',
'    type: INTERMEDIATE',
'    label: "Активы"',
'    source: computed',
'',
'  - id: EQUITY',
'    type: INPUT',
'    label: "Собственный капитал"',
'    value: 10000000',
'    min: 1000000',
'    max: 50000000',
'    source: manual',
'    enabled: true',
'',
'  - id: RETAINED_START',
'    type: INPUT',
'    label: "Нераспределённая прибыль на начало"',
'    value: 3500000',
'    min: 0',
'    max: 20000000',
'    source: manual',
'    enabled: true',
'',
'  - id: RETAINED_EARNINGS',
'    type: INTERMEDIATE',
'    label: "Нераспределённая прибыль"',
'    source: computed',
'',
'edges:',
'  - from: VOLUME',
'    to: REVENUE',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: PRICE',
'    to: REVENUE',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: VOLUME',
'    to: MATERIAL_COST',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: UNIT_MATERIAL',
'    to: MATERIAL_COST',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: BASE_MATERIAL_PRICE',
'    to: UNIT_MATERIAL',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: INFLATION',
'    to: UNIT_MATERIAL',
'    type: LIN',
'    coefficient: 0.03',
'',
'  - from: FX_RATE',
'    to: UNIT_MATERIAL',
'    type: LIN',
'    coefficient: 0.02',
'',
'  - from: TARIFFS',
'    to: UNIT_MATERIAL',
'    type: LIN',
'    coefficient: 0.05',
'',
'  - from: GEO_INDEX',
'    to: UNIT_MATERIAL',
'    type: LIN',
'    coefficient: 0.15',
'',
'  - from: SUPPLIER_RISK',
'    to: UNIT_MATERIAL',
'    type: THR',
'    coefficient: 1.0',
'    threshold: 0.3',
'    above: 1.4',
'    below: 1.0',
'',
'  - from: VOLUME',
'    to: ENERGY_COST',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: ENERGY_RATE',
'    to: ENERGY_COST',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: VOLUME',
'    to: LOGISTICS_COST',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: LOGISTICS_RATE',
'    to: LOGISTICS_COST',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: PROD_HEADCOUNT',
'    to: DIRECT_LABOR',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: PROD_AVG_SALARY',
'    to: DIRECT_LABOR',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: LABOR_INDEX',
'    to: DIRECT_LABOR',
'    type: LIN',
'    coefficient: 0.08',
'',
'  - from: VOLUME',
'    to: SCALE_EFFECT',
'    type: DIM',
'    coefficient: -0.02',
'',
'  - from: MATERIAL_COST',
'    to: COGS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: DIRECT_LABOR',
'    to: COGS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: ENERGY_COST',
'    to: COGS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: LOGISTICS_COST',
'    to: COGS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: DEFECT_RATE',
'    to: COGS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: SCALE_EFFECT',
'    to: COGS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: ADMIN_HEADCOUNT',
'    to: ADMIN_PAYROLL',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: ADMIN_AVG_SALARY',
'    to: ADMIN_PAYROLL',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: LABOR_INDEX',
'    to: ADMIN_PAYROLL',
'    type: LIN',
'    coefficient: 0.05',
'',
'  - from: ADMIN_PAYROLL',
'    to: ADMIN_EXP',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: RENT',
'    to: ADMIN_EXP',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: IT_EXP',
'    to: ADMIN_EXP',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: RD_EXP',
'    to: ADMIN_EXP',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: TRAINING_EXP',
'    to: ADMIN_EXP',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: MARKETING',
'    to: SELLING_EXP',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: LOGISTICS_COST',
'    to: SELLING_EXP',
'    type: LIN',
'    coefficient: 0.3',
'',
'  - from: ADMIN_HEADCOUNT',
'    to: EFFECTIVE_HEADCOUNT',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: ATTRITION',
'    to: EFFECTIVE_HEADCOUNT',
'    type: LIN',
'    coefficient: -0.01',
'    lag_days: 60',
'',
'  - from: FIXED_ASSETS',
'    to: DA',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: INTANGIBLE_ASSETS',
'    to: DA',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: DA_RATE',
'    to: DA',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: CAPACITY_UTIL',
'    to: WEAR',
'    type: LIN',
'    coefficient: 0.05',
'',
'  - from: TECH_OBSOLESCENCE',
'    to: WEAR',
'    type: LIN',
'    coefficient: 0.02',
'',
'  - from: CAPEX',
'    to: WEAR',
'    type: LIN',
'    coefficient: -0.01',
'',
'  - from: WEAR',
'    to: DA_RATE',
'    type: LIN',
'    coefficient: 0.03',
'',
'  - from: CB_RATE',
'    to: LOAN_RATE',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: BANK_SPREAD',
'    to: LOAN_RATE',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: LOANS',
'    to: INTEREST',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: LOAN_RATE',
'    to: INTEREST',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: LOANS',
'    to: DEBT_EBITDA',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: EBITDA',
'    to: DEBT_EBITDA',
'    type: LIN',
'    coefficient: -0.001',
'',
'  - from: PMI',
'    to: BUSINESS_ACTIVITY',
'    type: LIN',
'    coefficient: 0.015',
'',
'  - from: CCI',
'    to: BUSINESS_ACTIVITY',
'    type: LIN',
'    coefficient: 0.01',
'',
'  - from: CB_RATE',
'    to: BUSINESS_ACTIVITY',
'    type: LIN',
'    coefficient: -0.02',
'',
'  - from: SANCTIONS',
'    to: BUSINESS_ACTIVITY',
'    type: LIN',
'    coefficient: -0.10',
'',
'  - from: SPI',
'    to: ATTRITION',
'    type: EXP',
'    coefficient: 0.04',
'    lag_days: 90',
'',
'  - from: LABOR_INDEX',
'    to: ATTRITION',
'    type: LIN',
'    coefficient: 0.05',
'',
'  - from: ENGAGEMENT',
'    to: ATTRITION',
'    type: LIN',
'    coefficient: -0.10',
'',
'  - from: REVENUE',
'    to: GROSS_PROFIT',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: COGS',
'    to: GROSS_PROFIT',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: GROSS_PROFIT',
'    to: EBITDA',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: SELLING_EXP',
'    to: EBITDA',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: ADMIN_EXP',
'    to: EBITDA',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: EBITDA',
'    to: EBIT',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: DA',
'    to: EBIT',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: EBIT',
'    to: EBT',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: INTEREST',
'    to: EBT',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: INTEREST_INCOME',
'    to: EBT',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: OTHER_INCOME',
'    to: EBT',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: OTHER_EXP',
'    to: EBT',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: PENALTIES',
'    to: EBT',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: EBT',
'    to: NET_PROFIT',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: TAX',
'    to: NET_PROFIT',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: EBT',
'    to: TAX',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: TAX_RATE',
'    to: TAX',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: NET_PROFIT',
'    to: CFO',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: DA',
'    to: CFO',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: delta_RECEIVABLES',
'    to: CFO',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: delta_PAYABLES',
'    to: CFO',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: delta_INVENTORY',
'    to: CFO',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: CAPEX',
'    to: CFI',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: NEW_LOANS',
'    to: CFF',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: LOAN_REPAYMENT',
'    to: CFF',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: DIVIDENDS',
'    to: CFF',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: CFO',
'    to: FCF',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: CFI',
'    to: FCF',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: CFF',
'    to: FCF',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: CASH_START',
'    to: CASH',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: FCF',
'    to: CASH',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: INVENTORY',
'    to: CURRENT_ASSETS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: RECEIVABLES',
'    to: CURRENT_ASSETS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: CASH',
'    to: CURRENT_ASSETS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: CURRENT_ASSETS',
'    to: ASSETS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: FIXED_ASSETS',
'    to: ASSETS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: INTANGIBLE_ASSETS',
'    to: ASSETS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: RETAINED_START',
'    to: RETAINED_EARNINGS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: NET_PROFIT',
'    to: RETAINED_EARNINGS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: DIVIDENDS',
'    to: RETAINED_EARNINGS',
'    type: LIN',
'    coefficient: -1.0',
'',
'constraints:',
'  - node: NET_PROFIT',
'    operator: ">="',
'    value: 0',
'',
'  - node: NET_PROFIT',
'    operator: ">="',
'    value: 1000000'
].join('\n');
