var TEMPLATE_UNIVERSAL = [
    'project:',
    '  name: "Новая компания"',
    '  version: 3',
    '',
    '# ============================================================',
    '# НЕПРИКАСАЕМЫЕ — ФИНАНСОВЫЙ СКЕЛЕТ (TARGET / INTERMEDIATE)',
    '# ============================================================',
    '',
    'nodes:',
    '  - id: NET_PROFIT',
    '    type: TARGET',
    '    label: "Чистая прибыль"',
    '    source: computed',
    '',
    '  - id: EBT',
    '    type: INTERMEDIATE',
    '    label: "Прибыль до налогообложения"',
    '    source: computed',
    '    formula: "EBIT - INTEREST + OTHER_INCOME - OTHER_EXP - PENALTIES"',
    '',
    '  - id: TAX',
    '    type: INTERMEDIATE',
    '    label: "Налог на прибыль"',
    '    source: computed',
    '    formula: "MAX(0, EBT * TAX_RATE)"',
    '',
    '  - id: EBIT',
    '    type: INTERMEDIATE',
    '    label: "Операционная прибыль"',
    '    source: computed',
    '',
    '  - id: EBITDA',
    '    type: INTERMEDIATE',
    '    label: "EBITDA"',
    '    source: computed',
    '',
    '  - id: GROSS_PROFIT',
    '    type: INTERMEDIATE',
    '    label: "Валовая прибыль"',
    '    source: computed',
    '',
    '  - id: REVENUE',
    '    type: INTERMEDIATE',
    '    label: "Выручка"',
    '    source: computed',
    '    formula: "VOLUME * PRICE * SEASON"',
    '',
    '  - id: COGS',
    '    type: INTERMEDIATE',
    '    label: "Себестоимость"',
    '    source: computed',
    '',
    '  - id: SELLING_EXP',
    '    type: INTERMEDIATE',
    '    label: "Коммерческие расходы"',
    '    source: computed',
    '',
    '  - id: ADMIN_EXP',
    '    type: INTERMEDIATE',
    '    label: "Управленческие расходы"',
    '    source: computed',
    '',
    '  - id: DA',
    '    type: INTERMEDIATE',
    '    label: "Амортизация"',
    '    source: computed',
    '    formula: "(FIXED_ASSETS + INTANGIBLE_ASSETS) * DA_RATE"',
    '',
    '  - id: INTEREST',
    '    type: INTERMEDIATE',
    '    label: "Проценты к уплате"',
    '    source: computed',
    '    formula: "LOANS * LOAN_RATE"',
    '',
    '  - id: CFO',
    '    type: INTERMEDIATE',
    '    label: "Операционный денежный поток"',
    '    source: computed',
    '',
    '  - id: CFI',
    '    type: INTERMEDIATE',
    '    label: "Инвестиционный денежный поток"',
    '    source: computed',
    '',
    '  - id: CFF',
    '    type: INTERMEDIATE',
    '    label: "Финансовый денежный поток"',
    '    source: computed',
    '',
    '  - id: FCF',
    '    type: INTERMEDIATE',
    '    label: "Свободный денежный поток"',
    '    source: computed',
    '',
    '  - id: CASH',
    '    type: INTERMEDIATE',
    '    label: "Денежные средства"',
    '    source: computed',
    '    formula: "CASH_START + FCF"',
    '',
    '  - id: LOAN_RATE',
    '    type: INTERMEDIATE',
    '    label: "Средняя ставка по кредитам"',
    '    source: computed',
    '',
    '  - id: DEBT_EBITDA',
    '    type: INTERMEDIATE',
    '    label: "Долг/EBITDA"',
    '    source: computed',
    '',
    '  - id: CURRENT_ASSETS',
    '    type: INTERMEDIATE',
    '    label: "Оборотные активы"',
    '    source: computed',
    '',
    '  - id: ASSETS',
    '    type: INTERMEDIATE',
    '    label: "Активы"',
    '    source: computed',
    '',
    '  - id: RETAINED_EARNINGS',
    '    type: INTERMEDIATE',
    '    label: "Нераспределённая прибыль"',
    '    source: computed',
    '',
    '# ============================================================',
    '# БАЗОВЫЕ INPUT-УЗЛЫ (значение = 0, пользователь заполняет)',
    '# ============================================================',
    '',
    '  - id: PRICE',
    '    type: INPUT',
    '    label: "Цена"',
    '    value: 0',
    '    min: 0',
    '    max: 1000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: VOLUME',
    '    type: INPUT',
    '    label: "Объём продаж (ед/мес)"',
    '    value: 0',
    '    min: 0',
    '    max: 1000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: SEASON',
    '    type: INPUT',
    '    label: "Сезонность"',
    '    value: 1.0',
    '    min: 0.1',
    '    max: 3.0',
    '    source: manual',
    '    enabled: true',
    '',
    '# БЭКОФИС',
    '  - id: ADMIN_HEADCOUNT',
    '    type: INPUT',
    '    label: "Численность АУП"',
    '    value: 0',
    '    min: 0',
    '    max: 100',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: ADMIN_AVG_SALARY',
    '    type: INPUT',
    '    label: "Средняя ЗП АУП"',
    '    value: 0',
    '    min: 0',
    '    max: 300000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: ADMIN_PAYROLL',
    '    type: INTERMEDIATE',
    '    label: "ФОТ АУП"',
    '    source: computed',
    '    formula: "ADMIN_HEADCOUNT * ADMIN_AVG_SALARY"',
    '',
    '  - id: RENT',
    '    type: INPUT',
    '    label: "Аренда"',
    '    value: 0',
    '    min: 0',
    '    max: 1000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: IT_EXP',
    '    type: INPUT',
    '    label: "IT-расходы"',
    '    value: 0',
    '    min: 0',
    '    max: 500000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: LEGAL_COST',
    '    type: INPUT',
    '    label: "Юридические услуги"',
    '    value: 0',
    '    min: 0',
    '    max: 200000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: BANK_FEES',
    '    type: INPUT',
    '    label: "Комиссии банка"',
    '    value: 0',
    '    min: 0',
    '    max: 50000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: INSURANCE_COST',
    '    type: INPUT',
    '    label: "Страхование"',
    '    value: 0',
    '    min: 0',
    '    max: 200000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: UTILITIES',
    '    type: INPUT',
    '    label: "Коммунальные платежи"',
    '    value: 0',
    '    min: 0',
    '    max: 200000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: OFFICE_EXP',
    '    type: INPUT',
    '    label: "Офисные расходы"',
    '    value: 0',
    '    min: 0',
    '    max: 100000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: TRAINING_COST',
    '    type: INPUT',
    '    label: "Обучение персонала"',
    '    value: 0',
    '    min: 0',
    '    max: 500000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: TRAVEL_COST',
    '    type: INPUT',
    '    label: "Командировочные"',
    '    value: 0',
    '    min: 0',
    '    max: 300000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: RD_EXP',
    '    type: INPUT',
    '    label: "R&D расходы"',
    '    value: 0',
    '    min: 0',
    '    max: 1000000',
    '    source: manual',
    '    enabled: true',
    '',
    '# ПЕРСОНАЛ',
    '  - id: PROD_HEADCOUNT',
    '    type: INPUT',
    '    label: "Численность произв. персонала"',
    '    value: 0',
    '    min: 0',
    '    max: 500',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: PROD_AVG_SALARY',
    '    type: INPUT',
    '    label: "Средняя ЗП произв. персонала"',
    '    value: 0',
    '    min: 0',
    '    max: 200000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: DIRECT_LABOR',
    '    type: INTERMEDIATE',
    '    label: "ФОТ произв. персонала"',
    '    source: computed',
    '    formula: "PROD_HEADCOUNT * PROD_AVG_SALARY"',
    '',
    '  - id: OUTSOURCE_COST',
    '    type: INPUT',
    '    label: "Затраты на аутсорсинг"',
    '    value: 0',
    '    min: 0',
    '    max: 1000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: ATTRITION',
    '    type: INPUT',
    '    label: "Текучесть (%)"',
    '    value: 0',
    '    min: 0',
    '    max: 100',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: ENGAGEMENT',
    '    type: INPUT',
    '    label: "Вовлечённость (0-1)"',
    '    value: 0.5',
    '    min: 0',
    '    max: 1',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: BONUS_PROFIT_PCT',
    '    type: INPUT',
    '    label: "Премия (% от прибыли)"',
    '    value: 0',
    '    min: 0',
    '    max: 100',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: SALES_HEADCOUNT',
    '    type: INPUT',
    '    label: "Численность продавцов"',
    '    value: 0',
    '    min: 0',
    '    max: 200',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: SALES_AVG_SALARY',
    '    type: INPUT',
    '    label: "Средняя ЗП продавцов"',
    '    value: 0',
    '    min: 0',
    '    max: 200000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: WAREHOUSE_STAFF',
    '    type: INPUT',
    '    label: "Численность персонала склада"',
    '    value: 0',
    '    min: 0',
    '    max: 100',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: WAREHOUSE_AVG_SALARY',
    '    type: INPUT',
    '    label: "Средняя ЗП персонала склада"',
    '    value: 0',
    '    min: 0',
    '    max: 150000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: DEV_HEADCOUNT',
    '    type: INPUT',
    '    label: "Количество разработчиков"',
    '    value: 0',
    '    min: 0',
    '    max: 500',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: DEV_AVG_SALARY',
    '    type: INPUT',
    '    label: "Средняя ЗП разработчика"',
    '    value: 0',
    '    min: 0',
    '    max: 500000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: MONTHLY_RATE_PER_DEV',
    '    type: INPUT',
    '    label: "Ставка за разработчика в месяц"',
    '    value: 0',
    '    min: 0',
    '    max: 1000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: UTILIZATION',
    '    type: INPUT',
    '    label: "Утилизация (% оплачиваемого времени)"',
    '    value: 0',
    '    min: 0',
    '    max: 100',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: HOURLY_RATE',
    '    type: INPUT',
    '    label: "Ставка часа"',
    '    value: 0',
    '    min: 0',
    '    max: 10000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: HOURS_SOLD',
    '    type: INPUT',
    '    label: "Оплачиваемые часы"',
    '    value: 0',
    '    min: 0',
    '    max: 10000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: SPECIALIST_HEADCOUNT',
    '    type: INPUT',
    '    label: "Численность специалистов"',
    '    value: 0',
    '    min: 0',
    '    max: 200',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: SPECIALIST_AVG_SALARY',
    '    type: INPUT',
    '    label: "Средняя ЗП специалистов"',
    '    value: 0',
    '    min: 0',
    '    max: 250000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: AVG_CHECK',
    '    type: INPUT',
    '    label: "Средний чек"',
    '    value: 0',
    '    min: 0',
    '    max: 100000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: DEV_PAYROLL',
    '    type: INTERMEDIATE',
    '    label: "ФОТ разработчиков"',
    '    source: computed',
    '    formula: "DEV_HEADCOUNT * DEV_AVG_SALARY"',
    '',
    '  - id: SPECIALIST_PAYROLL',
    '    type: INTERMEDIATE',
    '    label: "ФОТ специалистов"',
    '    source: computed',
    '    formula: "SPECIALIST_HEADCOUNT * SPECIALIST_AVG_SALARY"',
    '',
    '  - id: SALES_PAYROLL',
    '    type: INTERMEDIATE',
    '    label: "ФОТ продавцов"',
    '    source: computed',
    '    formula: "SALES_HEADCOUNT * SALES_AVG_SALARY"',
    '',
    '  - id: WAREHOUSE_PAYROLL',
    '    type: INTERMEDIATE',
    '    label: "ФОТ склада"',
    '    source: computed',
    '    formula: "WAREHOUSE_STAFF * WAREHOUSE_AVG_SALARY"',
    '',
    '# МАРКЕТИНГ',
    '  - id: MARKETING',
    '    type: INPUT',
    '    label: "Маркетинг"',
    '    value: 0',
    '    min: 0',
    '    max: 10000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: COMPETITION',
    '    type: INPUT',
    '    label: "Конкуренция (0-1)"',
    '    value: 0.5',
    '    min: 0',
    '    max: 1',
    '    source: manual',
    '    enabled: true',
    '',
    '# ПРОИЗВОДСТВО',
    '  - id: UNIT_MATERIAL',
    '    type: INPUT',
    '    label: "Цена сырья за единицу"',
    '    value: 0',
    '    min: 0',
    '    max: 100000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: MATERIAL_COST',
    '    type: INTERMEDIATE',
    '    label: "Материальные затраты"',
    '    source: computed',
    '    formula: "VOLUME * UNIT_MATERIAL"',
    '',
    '  - id: ENERGY_COST',
    '    type: INPUT',
    '    label: "Энергозатраты"',
    '    value: 0',
    '    min: 0',
    '    max: 2000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: LOGISTICS_COST',
    '    type: INPUT',
    '    label: "Логистика"',
    '    value: 0',
    '    min: 0',
    '    max: 1000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: DEFECT_RATE',
    '    type: INPUT',
    '    label: "Брак (%)"',
    '    value: 0',
    '    min: 0',
    '    max: 100',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: DEFECT_COST',
    '    type: INTERMEDIATE',
    '    label: "Потери от брака"',
    '    source: computed',
    '    formula: "MATERIAL_COST * DEFECT_RATE / 100"',
    '',
    '  - id: WAREHOUSE_COST',
    '    type: INPUT',
    '    label: "Стоимость хранения"',
    '    value: 0',
    '    min: 0',
    '    max: 500000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: RETURN_RATE',
    '    type: INPUT',
    '    label: "Процент возвратов"',
    '    value: 0',
    '    min: 0',
    '    max: 100',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: CAPACITY',
    '    type: INPUT',
    '    label: "Производственная мощность"',
    '    value: 0',
    '    min: 0',
    '    max: 1000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: WEAR',
    '    type: INPUT',
    '    label: "Износ оборудования (0-1)"',
    '    value: 0',
    '    min: 0',
    '    max: 1',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: SUPPLIER_RISK',
    '    type: EXTERNAL',
    '    label: "Риск дефолта поставщика"',
    '    value: 0.05',
    '    min: 0',
    '    max: 1',
    '    source: manual',
    '    enabled: true',
    '',
    '# АКТИВЫ',
    '  - id: FIXED_ASSETS',
    '    type: INPUT',
    '    label: "Основные средства"',
    '    value: 0',
    '    min: 0',
    '    max: 100000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: INTANGIBLE_ASSETS',
    '    type: INPUT',
    '    label: "Нематериальные активы"',
    '    value: 0',
    '    min: 0',
    '    max: 100000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: DA_RATE',
    '    type: INPUT',
    '    label: "Норма амортизации"',
    '    value: 0.10',
    '    min: 0.01',
    '    max: 0.30',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: CAPEX',
    '    type: INPUT',
    '    label: "Капитальные затраты"',
    '    value: 0',
    '    min: 0',
    '    max: 10000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: INVENTORY',
    '    type: INPUT',
    '    label: "Товарные запасы"',
    '    value: 0',
    '    min: 0',
    '    max: 10000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: RECEIVABLES',
    '    type: INPUT',
    '    label: "Дебиторская задолженность"',
    '    value: 0',
    '    min: 0',
    '    max: 10000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: PAYABLES',
    '    type: INPUT',
    '    label: "Кредиторская задолженность"',
    '    value: 0',
    '    min: 0',
    '    max: 10000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: CASH_START',
    '    type: INPUT',
    '    label: "Остаток денег на начало"',
    '    value: 0',
    '    min: 0',
    '    max: 100000000',
    '    source: manual',
    '    enabled: true',
    '',
    '# ДОЛГ',
    '  - id: LOANS',
    '    type: INPUT',
    '    label: "Кредитный портфель"',
    '    value: 0',
    '    min: 0',
    '    max: 100000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: NEW_LOANS',
    '    type: INPUT',
    '    label: "Новые кредиты"',
    '    value: 0',
    '    min: 0',
    '    max: 10000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: LOAN_REPAYMENT',
    '    type: INPUT',
    '    label: "Погашение кредитов"',
    '    value: 0',
    '    min: 0',
    '    max: 10000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: BANK_SPREAD',
    '    type: INPUT',
    '    label: "Спред банка"',
    '    value: 0.03',
    '    min: 0.01',
    '    max: 0.10',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: DIVIDENDS',
    '    type: INPUT',
    '    label: "Дивиденды"',
    '    value: 0',
    '    min: 0',
    '    max: 10000000',
    '    source: manual',
    '    enabled: true',
    '',
    '# ВНЕШНИЕ ФАКТОРЫ',
    '  - id: CB_RATE',
    '    type: EXTERNAL',
    '    label: "Ключевая ставка ЦБ"',
    '    value: 0.21',
    '    min: 0.01',
    '    max: 0.50',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: INFLATION',
    '    type: EXTERNAL',
    '    label: "Инфляция"',
    '    value: 0.07',
    '    min: 0',
    '    max: 0.50',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: FX_RATE',
    '    type: EXTERNAL',
    '    label: "Курс USD/RUB"',
    '    value: 95',
    '    min: 50',
    '    max: 150',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: PMI',
    '    type: EXTERNAL',
    '    label: "Индекс PMI"',
    '    value: 52',
    '    min: 30',
    '    max: 70',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: CCI',
    '    type: EXTERNAL',
    '    label: "Потребительская уверенность"',
    '    value: -8',
    '    min: -50',
    '    max: 20',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: LABOR_INDEX',
    '    type: EXTERNAL',
    '    label: "Индекс рынка труда"',
    '    value: 0.8',
    '    min: 0.3',
    '    max: 1.5',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: GEO_INDEX',
    '    type: EXTERNAL',
    '    label: "Геополитический индекс"',
    '    value: 0.7',
    '    min: 0',
    '    max: 1',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: SANCTIONS',
    '    type: EXTERNAL',
    '    label: "Санкционный индекс"',
    '    value: 0.7',
    '    min: 0',
    '    max: 1',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: TARIFFS',
    '    type: EXTERNAL',
    '    label: "Тарифы монополий"',
    '    value: 1.05',
    '    min: 0.8',
    '    max: 1.5',
    '    source: manual',
    '    enabled: true',
    '',
    '# НАЛОГИ',
    '  - id: TAX_RATE',
    '    type: INPUT',
    '    label: "Ставка налога на прибыль"',
    '    value: 0.25',
    '    min: 0',
    '    max: 0.50',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: PENALTIES',
    '    type: INPUT',
    '    label: "Штрафы и пени"',
    '    value: 0',
    '    min: 0',
    '    max: 500000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: OTHER_INCOME',
    '    type: INPUT',
    '    label: "Прочие доходы"',
    '    value: 0',
    '    min: 0',
    '    max: 10000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: OTHER_EXP',
    '    type: INPUT',
    '    label: "Прочие расходы"',
    '    value: 0',
    '    min: 0',
    '    max: 10000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: INTEREST_INCOME',
    '    type: INPUT',
    '    label: "Проценты к получению"',
    '    value: 0',
    '    min: 0',
    '    max: 1000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: delta_RECEIVABLES',
    '    type: INPUT',
    '    label: "Изменение дебиторской задолженности"',
    '    value: 0',
    '    min: -10000000',
    '    max: 10000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: delta_PAYABLES',
    '    type: INPUT',
    '    label: "Изменение кредиторской задолженности"',
    '    value: 0',
    '    min: -10000000',
    '    max: 10000000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: delta_INVENTORY',
    '    type: INPUT',
    '    label: "Изменение запасов"',
    '    value: 0',
    '    min: -10000000',
    '    max: 10000000',
    '    source: manual',
    '    enabled: true',
    '',
    '# ============================================================',
    '# СВЯЗИ — ПОЛНЫЙ НАБОР',
    '# ============================================================',
    '',
    'edges:',
    '# REVENUE',
    '  - from: PRICE',
    '    to: REVENUE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: VOLUME',
    '    to: REVENUE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: DEV_PAYROLL',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: SPECIALIST_PAYROLL',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: SALES_PAYROLL',
    '    to: SELLING_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: WAREHOUSE_PAYROLL',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '# COGS',
    '  - from: MATERIAL_COST',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: DIRECT_LABOR',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: ENERGY_COST',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: LOGISTICS_COST',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 0.7',
    '',
    '  - from: DEFECT_COST',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: WAREHOUSE_COST',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: OUTSOURCE_COST',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '# OPEX',
    '  - from: ADMIN_PAYROLL',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: RENT',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: IT_EXP',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: RD_EXP',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: TRAINING_COST',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: LEGAL_COST',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: BANK_FEES',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: INSURANCE_COST',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: UTILITIES',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: OFFICE_EXP',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: TRAVEL_COST',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: MARKETING',
    '    to: SELLING_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: LOGISTICS_COST',
    '    to: SELLING_EXP',
    '    type: LIN',
    '    coefficient: 0.3',
    '',
    '# P&L цепочка',
    '  - from: REVENUE',
    '    to: GROSS_PROFIT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: COGS',
    '    to: GROSS_PROFIT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: GROSS_PROFIT',
    '    to: EBITDA',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: SELLING_EXP',
    '    to: EBITDA',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: ADMIN_EXP',
    '    to: EBITDA',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: EBITDA',
    '    to: EBIT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: DA',
    '    to: EBIT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: EBIT',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: INTEREST',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: INTEREST_INCOME',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: OTHER_INCOME',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: OTHER_EXP',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: PENALTIES',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: EBT',
    '    to: NET_PROFIT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: TAX',
    '    to: NET_PROFIT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '# КРЕДИТЫ',
    '  - from: CB_RATE',
    '    to: LOAN_RATE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: BANK_SPREAD',
    '    to: LOAN_RATE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: NEW_LOANS',
    '    to: CFF',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: LOAN_REPAYMENT',
    '    to: CFF',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: DIVIDENDS',
    '    to: CFF',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '# ДЕНЕЖНЫЙ ПОТОК',
    '  - from: NET_PROFIT',
    '    to: CFO',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: DA',
    '    to: CFO',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: delta_RECEIVABLES',
    '    to: CFO',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: delta_PAYABLES',
    '    to: CFO',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: delta_INVENTORY',
    '    to: CFO',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: CAPEX',
    '    to: CFI',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: CFO',
    '    to: FCF',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: CFI',
    '    to: FCF',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: CFF',
    '    to: FCF',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '# БАЛАНС',
    '  - from: INVENTORY',
    '    to: CURRENT_ASSETS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: RECEIVABLES',
    '    to: CURRENT_ASSETS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: CASH',
    '    to: CURRENT_ASSETS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: CURRENT_ASSETS',
    '    to: ASSETS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: FIXED_ASSETS',
    '    to: ASSETS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: INTANGIBLE_ASSETS',
    '    to: ASSETS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: NET_PROFIT',
    '    to: RETAINED_EARNINGS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: DIVIDENDS',
    '    to: RETAINED_EARNINGS',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: MONTHLY_RATE_PER_DEV',
    '    to: REVENUE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: UTILIZATION',
    '    to: REVENUE',
    '    type: LIN',
    '    coefficient: 0.01',
    '',
    '  - from: HOURLY_RATE',
    '    to: REVENUE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: HOURS_SOLD',
    '    to: REVENUE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: AVG_CHECK',
    '    to: REVENUE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: SEASON',
    '    to: REVENUE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    'constraints:',
    '  - node: NET_PROFIT',
    '    operator: ">="',
    '    value: 0',
    '',
    '  - node: CASH',
    '    operator: ">="',
    '    value: 0',
].join('\n');
