var TEMPLATE_SERVICES = [
    'project:',
    '  name: "Сервисная компания"',
    '  version: 2',
    '',
    'nodes:',
    '  - id: NET_PROFIT',
    '    type: TARGET',
    '    label: "Чистая прибыль"',
    '    source: computed',
    '',
    '  - id: EBT',
    '    type: INTERMEDIATE',
    '    label: "Прибыль до налогообложения"',
    '    source: computed',
    '',
    '  - id: TAX',
    '    type: INTERMEDIATE',
    '    label: "Налог на прибыль"',
    '    source: computed',
    '    formula: "MAX(0, EBT * TAX_RATE)"',
    '',
    '  - id: TAX_RATE',
    '    type: INPUT',
    '    label: "Ставка налога на прибыль"',
    '    value: 0.20,',
'    min: 0.03,',
'    max: 0.25,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: EBITDA',
    '    type: INTERMEDIATE',
    '    label: "EBITDA"',
    '    source: computed',
    '',
    '  - id: EBIT',
    '    type: INTERMEDIATE',
    '    label: "Операционная прибыль"',
    '    source: computed',
    '',
    '  - id: INTEREST',
    '    type: INTERMEDIATE',
    '    label: "Проценты к уплате"',
    '    source: computed',
    '    formula: "LOANS * LOAN_RATE"',
    '',
    '  - id: GROSS_PROFIT',
    '    type: INTERMEDIATE',
    '    label: "Валовая прибыль"',
    '    source: computed',
    '',
    '  - id: REVENUE',
    '    type: INTERMEDIATE',
    '    label: "Выручка"',
    '    source: computed',
    '    formula: "HOURS_SOLD * HOURLY_RATE"',
    '',
    '  - id: HOURLY_RATE',
    '    type: INPUT',
    '    label: "Средняя ставка часа (руб)"',
    '    value: 3500,',
'    min: 2000,',
'    max: 6000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: HOURS_SOLD',
    '    type: INPUT',
    '    label: "Оплачиваемые часы (в месяц)"',
    '    value: 1800,',
'    min: 500,',
'    max: 4000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: COGS',
    '    type: INTERMEDIATE',
    '    label: "Прямые расходы"',
    '    source: computed',
    '',
    '  - id: ADMIN_EXP',
    '    type: INTERMEDIATE',
    '    label: "Административные расходы"',
    '    source: computed',
    '',
    '  - id: SPECIALIST_PAYROLL',
    '    type: INTERMEDIATE',
    '    label: "ФОТ специалистов"',
    '    source: computed',
    '    formula: "SPECIALIST_HEADCOUNT * SPECIALIST_AVG_SALARY"',
    '',
    '  - id: SPECIALIST_HEADCOUNT',
    '    type: INPUT',
    '    label: "Численность специалистов"',
    '    value: 15,',
'    min: 3,',
'    max: 50,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: SPECIALIST_AVG_SALARY',
    '    type: INPUT',
    '    label: "Средняя ЗП специалиста"',
    '    value: 95000,',
'    min: 60000,',
'    max: 150000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: ADMIN_PAYROLL',
    '    type: INTERMEDIATE',
    '    label: "ФОТ административного персонала"',
    '    source: computed',
    '    formula: "ADMIN_HEADCOUNT * ADMIN_AVG_SALARY"',
    '',
    '  - id: ADMIN_HEADCOUNT',
    '    type: INPUT',
    '    label: "Численность АУП"',
    '    value: 5,',
'    min: 2,',
'    max: 15,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: ADMIN_AVG_SALARY',
    '    type: INPUT',
    '    label: "Средняя ЗП АУП"',
    '    value: 100000,',
'    min: 70000,',
'    max: 150000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: MARKETING',
    '    type: INPUT',
    '    label: "Маркетинг и привлечение клиентов"',
    '    value: 200000,',
'    min: 50000,',
'    max: 800000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: RENT',
    '    type: INPUT',
    '    label: "Аренда офиса"',
    '    value: 250000,',
'    min: 100000,',
'    max: 600000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: IT_EXP',
    '    type: INPUT',
    '    label: "IT-расходы и подписки"',
    '    value: 120000,',
'    min: 30000,',
'    max: 300000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: TRAINING_EXP',
    '    type: INPUT',
    '    label: "Обучение и сертификация"',
    '    value: 80000,',
'    min: 20000,',
'    max: 300000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: FIXED_ASSETS',
    '    type: INPUT',
    '    label: "Основные средства (оборудование, мебель)"',
    '    value: 2000000,',
'    min: 500000,',
'    max: 10000000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: DA',
    '    type: INTERMEDIATE',
    '    label: "Амортизация"',
    '    source: computed',
    '    formula: "FIXED_ASSETS * 0.15"',
    '',
    '  - id: LOANS',
    '    type: INPUT',
    '    label: "Кредитный портфель"',
    '    value: 1000000,',
'    min: 0,',
'    max: 10000000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: LOAN_RATE',
    '    type: INTERMEDIATE',
    '    label: "Средняя ставка по кредитам"',
    '    source: computed',
    '',
    '  - id: CB_RATE',
    '    type: EXTERNAL',
    '    label: "Ключевая ставка ЦБ"',
    '    value: 0.18,',
'    min: 0.05,',
'    max: 0.25,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: BANK_SPREAD',
    '    type: INPUT',
    '    label: "Спред банка"',
    '    value: 0.03,',
'    min: 0.01,',
'    max: 0.06,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: FCF',
    '    type: INTERMEDIATE',
    '    label: "Свободный денежный поток"',
    '    source: computed',
    '',
    '  - id: CFO',
    '    type: INTERMEDIATE',
    '    label: "Операционный денежный поток"',
    '    source: computed',
    '',
    '  - id: CASH',
    '    type: INTERMEDIATE',
    '    label: "Денежные средства"',
    '    source: computed',
    '    formula: "CASH_START + FCF"',
    '',
    '  - id: CASH_START',
    '    type: INPUT',
    '    label: "Остаток денег на начало"',
    '    value: 1500000,',
'    min: 0,',
'    max: 10000000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: RECEIVABLES',
    '    type: INPUT',
    '    label: "Дебиторская задолженность"',
    '    value: 1200000,',
'    min: 0,',
'    max: 5000000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: PAYABLES',
    '    type: INPUT',
    '    label: "Кредиторская задолженность"',
    '    value: 500000,',
'    min: 0,',
'    max: 3000000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: INFLATION',
'    type: EXTERNAL',
'    label: "Инфляция"',
'    value: 0.07',
'    min: 0.03',
'    max: 0.20',
'    source: manual',
'    enabled: true',
'',
'  - id: CCI',
'    type: EXTERNAL',
'    label: "Потребительская уверенность"',
'    value: -8',
'    min: -40',
'    max: 10',
'    source: manual',
'    enabled: true',
'',
'  - id: HOUSEHOLD_INCOME',
'    type: EXTERNAL',
'    label: "Доходы населения"',
'    value: 55000',
'    min: 30000',
'    max: 80000',
'    source: manual',
'    enabled: true',
'',
'  - id: LABOR_INDEX',
'    type: EXTERNAL',
'    label: "Индекс рынка труда"',
'    value: 0.8',
'    min: 0.5',
'    max: 1.5',
'    source: manual',
'    enabled: true',
'',
'  - id: GEO_INDEX',
'    type: EXTERNAL',
'    label: "Геополитический индекс"',
'    value: 0.7',
'    min: 0',
'    max: 1.0',
'    source: manual',
'    enabled: true',
'',
    '  - id: PENALTIES',
    '    type: INPUT',
    '    label: "Штрафы и пени"',
    '    value: 0,',
'    min: 0,',
'    max: 2000000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: OTHER_INCOME',
    '    type: INPUT',
    '    label: "Прочие доходы"',
    '    value: 50000,',
'    min: 0,',
'    max: 300000,',
'    source: manual',
    '    enabled: true',
    '',
    '  - id: OTHER_EXP',
    '    type: INPUT',
    '    label: "Прочие расходы"',
    '    value: 80000,',
'    min: 0,',
'    max: 300000,',
'    source: manual',
    '    enabled: true',
    '',
    'edges:',
    '  - from: SPECIALIST_PAYROLL',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: TRAINING_EXP',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 0.5',
    '',
    '  - from: TRAINING_EXP',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 0.5',
    '',
    '  - from: ADMIN_PAYROLL',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: RENT',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: IT_EXP',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: MARKETING',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: CB_RATE',
    '    to: LOAN_RATE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: BANK_SPREAD',
    '    to: LOAN_RATE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: REVENUE',
    '    to: GROSS_PROFIT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: COGS',
    '    to: GROSS_PROFIT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: GROSS_PROFIT',
    '    to: EBITDA',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: ADMIN_EXP',
    '    to: EBITDA',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: EBITDA',
    '    to: EBIT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: DA',
    '    to: EBIT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: EBIT',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: INTEREST',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: OTHER_INCOME',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: OTHER_EXP',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: PENALTIES',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: EBT',
    '    to: NET_PROFIT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: TAX',
    '    to: NET_PROFIT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: NET_PROFIT',
    '    to: CFO',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: DA',
    '    to: CFO',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: CASH_START',
    '    to: CASH',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: FCF',
    '    to: CASH',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: CFO',
    '    to: FCF',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    'constraints:',
    '  - node: NET_PROFIT',
    '    operator: ">="',
    '    value: 0',
    ''].join('\n');
