var TEMPLATE_PRODUCTION = [
'project:',
'  name: "Производственная компания"',
'  version: 2',
'',
'nodes:',
'  - id: NET_PROFIT',
'    type: TARGET',
'    label: "Чистая прибыль"',
'    source: computed',
'',
'  - id: EBT',
'    type: INTERMEDIATE',
'    label: "Прибыль до налогообложения"',
'    source: computed',
'',
'  - id: TAX',
'    type: INTERMEDIATE',
'    label: "Налог на прибыль"',
'    source: computed',
'    formula: "MAX(0, EBT * TAX_RATE)"',
'',
'  - id: TAX_RATE',
'    type: INPUT',
'    label: "Ставка налога на прибыль"',
'    value: 0.20',
'    min: 0.03',
'    max: 0.25',
'    source: manual',
'    enabled: true',
'',
'  - id: EBITDA',
'    type: INTERMEDIATE',
'    label: "EBITDA"',
'    source: computed',
'',
'  - id: DA',
'    type: INTERMEDIATE',
'    label: "Амортизация"',
'    source: computed',
'    formula: "(FIXED_ASSETS + INTANGIBLE_ASSETS) * DA_RATE"',
'',
'  - id: DA_RATE',
'    type: INPUT',
'    label: "Норма амортизации"',
'    value: 0.10',
'    min: 0.05',
'    max: 0.25',
'    source: manual',
'    enabled: true',
'',
'  - id: EBIT',
'    type: INTERMEDIATE',
'    label: "Операционная прибыль"',
'    source: computed',
'',
'  - id: INTEREST',
'    type: INTERMEDIATE',
'    label: "Проценты к уплате"',
'    source: computed',
'    formula: "LOANS * LOAN_RATE"',
'',
'  - id: GROSS_PROFIT',
'    type: INTERMEDIATE',
'    label: "Валовая прибыль"',
'    source: computed',
'',
'  - id: REVENUE',
'    type: INTERMEDIATE',
'    label: "Выручка"',
'    source: computed',
'    formula: "VOLUME * PRICE"',
'',
'  - id: COGS',
'    type: INTERMEDIATE',
'    label: "Себестоимость продаж"',
'    source: computed',
'',
'  - id: SELLING_EXP',
'    type: INTERMEDIATE',
'    label: "Коммерческие расходы"',
'    source: computed',
'',
'  - id: ADMIN_EXP',
'    type: INTERMEDIATE',
'    label: "Управленческие расходы"',
'    source: computed',
'',
'  - id: PRICE',
'    type: INPUT',
'    label: "Цена единицы продукции"',
'    value: 5000',
'    min: 3000',
'    max: 8000',
'    source: manual',
'    enabled: true',
'',
'  - id: VOLUME',
'    type: INPUT',
'    label: "Объём производства (ед/мес)"',
'    value: 2000',
'    min: 500',
'    max: 5000',
'    source: manual',
'    enabled: true',
'',
'  - id: MARKETING',
'    type: INPUT',
'    label: "Маркетинг и продвижение"',
'    value: 300000',
'    min: 100000',
'    max: 1000000',
'    source: manual',
'    enabled: true',
'',
'  - id: MATERIAL_COST',
'    type: INTERMEDIATE',
'    label: "Сырьё и материалы"',
'    source: computed',
'    formula: "VOLUME * UNIT_MATERIAL"',
'',
'  - id: UNIT_MATERIAL',
'    type: INPUT',
'    label: "Стоимость сырья на единицу"',
'    value: 1800',
'    min: 1200',
'    max: 2500',
'    source: manual',
'    enabled: true',
'',
'  - id: DIRECT_LABOR',
'    type: INTERMEDIATE',
'    label: "ФОТ производственного персонала"',
'    source: computed',
'    formula: "PROD_HEADCOUNT * PROD_AVG_SALARY"',
'',
'  - id: PROD_HEADCOUNT',
'    type: INPUT',
'    label: "Численность производственного персонала"',
'    value: 45',
'    min: 20',
'    max: 100',
'    source: manual',
'    enabled: true',
'',
'  - id: PROD_AVG_SALARY',
'    type: INPUT',
'    label: "Средняя ЗП производственного персонала"',
'    value: 65000',
'    min: 45000',
'    max: 90000',
'    source: manual',
'    enabled: true',
'',
'  - id: ENERGY_COST',
'    type: INPUT',
'    label: "Энергозатраты (электричество, вода, газ)"',
'    value: 500000',
'    min: 200000',
'    max: 1000000',
'    source: manual',
'    enabled: true',
'',
'  - id: LOGISTICS_COST',
'    type: INPUT',
'    label: "Логистика и доставка"',
'    value: 350000',
'    min: 150000',
'    max: 700000',
'    source: manual',
'    enabled: true',
'',
'  - id: DEFECT_RATE',
'    type: INPUT',
'    label: "Брак (% от объёма)"',
'    value: 0.03',
'    min: 0.01',
'    max: 0.08',
'    source: manual',
'    enabled: true',
'',
'  - id: ADMIN_PAYROLL',
'    type: INTERMEDIATE',
'    label: "ФОТ административного персонала"',
'    source: computed',
'    formula: "ADMIN_HEADCOUNT * ADMIN_AVG_SALARY"',
'',
'  - id: ADMIN_HEADCOUNT',
'    type: INPUT',
'    label: "Численность АУП"',
'    value: 12',
'    min: 5',
'    max: 30',
'    source: manual',
'    enabled: true',
'',
'  - id: ADMIN_AVG_SALARY',
'    type: INPUT',
'    label: "Средняя ЗП АУП"',
'    value: 90000',
'    min: 60000',
'    max: 130000',
'    source: manual',
'    enabled: true',
'',
'  - id: RENT',
'    type: INPUT',
'    label: "Аренда производственных и офисных помещений"',
'    value: 600000',
'    min: 300000',
'    max: 1200000',
'    source: manual',
'    enabled: true',
'',
'  - id: IT_EXP',
'    type: INPUT',
'    label: "IT-расходы и ПО"',
'    value: 80000',
'    min: 30000',
'    max: 200000',
'    source: manual',
'    enabled: true',
'',
'  - id: FIXED_ASSETS',
'    type: INPUT',
'    label: "Основные средства (оборудование, здания)"',
'    value: 25000000',
'    min: 5000000',
'    max: 100000000',
'    source: manual',
'    enabled: true',
'',
'  - id: INTANGIBLE_ASSETS',
'    type: INPUT',
'    label: "Нематериальные активы (патенты, лицензии)"',
'    value: 1000000',
'    min: 0',
'    max: 10000000',
'    source: manual',
'    enabled: true',
'',
'  - id: CAPEX',
'    type: INPUT',
'    label: "Капитальные затраты на период"',
'    value: 2000000',
'    min: 0',
'    max: 10000000',
'    source: manual',
'    enabled: true',
'',
'  - id: LOANS',
'    type: INPUT',
'    label: "Кредитный портфель"',
'    value: 8000000',
'    min: 0',
'    max: 50000000',
'    source: manual',
'    enabled: true',
'',
'  - id: LOAN_RATE',
'    type: INTERMEDIATE',
'    label: "Средняя ставка по кредитам"',
'    source: computed',
'',
'  - id: CB_RATE',
'    type: EXTERNAL',
'    label: "Ключевая ставка ЦБ"',
'    value: 0.18',
'    min: 0.05',
'    max: 0.25',
'    source: manual',
'    enabled: true',
'',
'  - id: BANK_SPREAD',
'    type: INPUT',
'    label: "Спред банка"',
'    value: 0.03',
'    min: 0.01',
'    max: 0.06',
'    source: manual',
'    enabled: true',
'',
'  - id: FCF',
'    type: INTERMEDIATE',
'    label: "Свободный денежный поток"',
'    source: computed',
'',
'  - id: CFO',
'    type: INTERMEDIATE',
'    label: "Операционный денежный поток"',
'    source: computed',
'',
'  - id: CFI',
'    type: INTERMEDIATE',
'    label: "Инвестиционный денежный поток"',
'    source: computed',
'',
'  - id: CFF',
'    type: INTERMEDIATE',
'    label: "Финансовый денежный поток"',
'    source: computed',
'',
'  - id: CASH',
'    type: INTERMEDIATE',
'    label: "Денежные средства"',
'    source: computed',
'    formula: "CASH_START + FCF"',
'',
'  - id: CASH_START',
'    type: INPUT',
'    label: "Остаток денег на начало"',
'    value: 3000000',
'    min: 0',
'    max: 20000000',
'    source: manual',
'    enabled: true',
'',
'  - id: INVENTORY',
'    type: INPUT',
'    label: "Запасы готовой продукции и сырья"',
'    value: 4000000',
'    min: 1000000',
'    max: 15000000',
'    source: manual',
'    enabled: true',
'',
'  - id: RECEIVABLES',
'    type: INPUT',
'    label: "Дебиторская задолженность"',
'    value: 3500000',
'    min: 500000',
'    max: 10000000',
'    source: manual',
'    enabled: true',
'',
'  - id: PAYABLES',
'    type: INPUT',
'    label: "Кредиторская задолженность"',
'    value: 2500000',
'    min: 500000',
'    max: 8000000',
'    source: manual',
'    enabled: true',
'',
'  - id: INFLATION',
'    type: EXTERNAL',
'    label: "Инфляция"',
'    value: 0.07',
'    min: 0.03',
'    max: 0.20',
'    source: manual',
'    enabled: true',
'',
'  - id: FX_RATE',
'    type: EXTERNAL',
'    label: "Курс USD/RUB"',
'    value: 95',
'    min: 70',
'    max: 130',
'    source: manual',
'    enabled: true',
'',
'  - id: INFLATION',
'    type: EXTERNAL',
'    label: "Инфляция"',
'    value: 0.07',
'    min: 0.03',
'    max: 0.20',
'    source: manual',
'    enabled: true',
'',
'  - id: FX_RATE',
'    type: EXTERNAL',
'    label: "Курс USD/RUB"',
'    value: 95',
'    min: 70',
'    max: 130',
'    source: manual',
'    enabled: true',
'',
'  - id: PMI',
'    type: EXTERNAL',
'    label: "Индекс PMI"',
'    value: 52',
'    min: 40',
'    max: 65',
'    source: manual',
'    enabled: true',
'',
'  - id: TARIFFS',
'    type: EXTERNAL',
'    label: "Тарифы монополий"',
'    value: 1.05',
'    min: 0.9',
'    max: 1.3',
'    source: manual',
'    enabled: true',
'',
'  - id: GEO_INDEX',
'    type: EXTERNAL',
'    label: "Геополитический индекс"',
'    value: 0.7',
'    min: 0',
'    max: 1.0',
'    source: manual',
'    enabled: true',
'',
'  - id: SUPPLIER_RISK',
'    type: EXTERNAL',
'    label: "Риск дефолта поставщика"',
'    value: 0.05',
'    min: 0',
'    max: 1.0',
'    source: manual',
'    enabled: true',
'',
'  - id: LABOR_INDEX',
'    type: EXTERNAL',
'    label: "Индекс рынка труда"',
'    value: 0.8',
'    min: 0.5',
'    max: 1.5',
'    source: manual',
'    enabled: true',
'',
'  - id: PENALTIES',
'    type: INPUT',
'    label: "Штрафы и пени"',
'    value: 0',
'    min: 0',
'    max: 5000000',
'    source: manual',
'    enabled: true',
'',
'  - id: OTHER_INCOME',
'    type: INPUT',
'    label: "Прочие доходы"',
'    value: 100000',
'    min: 0',
'    max: 500000',
'    source: manual',
'    enabled: true',
'',
'  - id: OTHER_EXP',
'    type: INPUT',
'    label: "Прочие расходы"',
'    value: 150000',
'    min: 0',
'    max: 500000',
'    source: manual',
'    enabled: true',
'',
'edges:',
'  - from: MATERIAL_COST',
'    to: COGS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: DIRECT_LABOR',
'    to: COGS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: ENERGY_COST',
'    to: COGS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: LOGISTICS_COST',
'    to: COGS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: DEFECT_RATE',
'    to: COGS',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: ADMIN_PAYROLL',
'    to: ADMIN_EXP',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: RENT',
'    to: ADMIN_EXP',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: IT_EXP',
'    to: ADMIN_EXP',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: MARKETING',
'    to: SELLING_EXP',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: LOGISTICS_COST',
'    to: SELLING_EXP',
'    type: LIN',
'    coefficient: 0.3',
'',
'  - from: CB_RATE',
'    to: LOAN_RATE',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: BANK_SPREAD',
'    to: LOAN_RATE',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: REVENUE',
'    to: GROSS_PROFIT',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: COGS',
'    to: GROSS_PROFIT',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: GROSS_PROFIT',
'    to: EBITDA',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: SELLING_EXP',
'    to: EBITDA',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: ADMIN_EXP',
'    to: EBITDA',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: EBITDA',
'    to: EBIT',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: DA',
'    to: EBIT',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: EBIT',
'    to: EBT',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: INTEREST',
'    to: EBT',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: OTHER_INCOME',
'    to: EBT',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: OTHER_EXP',
'    to: EBT',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: PENALTIES',
'    to: EBT',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: EBT',
'    to: NET_PROFIT',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: TAX',
'    to: NET_PROFIT',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: NET_PROFIT',
'    to: CFO',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: DA',
'    to: CFO',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: CAPEX',
'    to: CFI',
'    type: LIN',
'    coefficient: -1.0',
'',
'  - from: CFO',
'    to: FCF',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: CFI',
'    to: FCF',
'    type: LIN',
'    coefficient: 1.0',
'',
'  - from: CFF',
'    to: FCF',
'    type: LIN',
'    coefficient: 1.0',
'',
'constraints:',
'  - node: NET_PROFIT',
'    operator: ">="',
'    value: 0',
''].join('\n');
