var TEMPLATE_IT = [
    'project:',
    '  name: "IT-компания"',
    '  version: 2',
    '',
    'nodes:',
    '  - id: NET_PROFIT',
    '    type: TARGET',
    '    label: "Чистая прибыль"',
    '    source: computed',
    '',
    '  - id: EBT',
    '    type: INTERMEDIATE',
    '    label: "Прибыль до налогообложения"',
    '    source: computed',
    '',
    '  - id: TAX',
    '    type: INTERMEDIATE',
    '    label: "Налог на прибыль"',
    '    source: computed',
    '    formula: "MAX(0, EBT * TAX_RATE)"',
    '',
    '  - id: TAX_RATE',
    '    type: INPUT',
    '    label: "Ставка налога на прибыль (льготная 3%)"',
    '    value: 0.03,',
    '    min: 0,',
    '    max: 0.20,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: EBITDA',
    '    type: INTERMEDIATE',
    '    label: "EBITDA"',
    '    source: computed',
    '',
    '  - id: EBIT',
    '    type: INTERMEDIATE',
    '    label: "Операционная прибыль"',
    '    source: computed',
    '',
    '  - id: INTEREST',
    '    type: INTERMEDIATE',
    '    label: "Проценты к уплате"',
    '    source: computed',
    '    formula: "LOANS * LOAN_RATE"',
    '',
    '  - id: REVENUE',
    '    type: INTERMEDIATE',
    '    label: "Выручка"',
    '    source: computed',
    '    formula: "DEV_HEADCOUNT * MONTHLY_RATE_PER_DEV"',
    '',
    '  - id: DEV_HEADCOUNT',
    '    type: INPUT',
    '    label: "Количество разработчиков"',
    '    value: 25,',
    '    min: 5,',
    '    max: 100,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: MONTHLY_RATE_PER_DEV',
    '    type: INPUT',
    '    label: "Ставка за разработчика в месяц"',
    '    value: 280000,',
    '    min: 150000,',
    '    max: 500000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: UTILIZATION',
    '    type: INPUT',
    '    label: "Утилизация (% оплачиваемого времени)"',
    '    value: 0.80,',
    '    min: 0.60,',
    '    max: 0.95,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: COGS',
    '    type: INTERMEDIATE',
    '    label: "Прямые расходы"',
    '    source: computed',
    '',
    '  - id: ADMIN_EXP',
    '    type: INTERMEDIATE',
    '    label: "Административные расходы"',
    '    source: computed',
    '',
    '  - id: DEV_PAYROLL',
    '    type: INTERMEDIATE',
    '    label: "ФОТ разработчиков (включая налоги)"',
    '    source: computed',
    '    formula: "DEV_HEADCOUNT * DEV_AVG_SALARY * 1.3"',
    '',
    '  - id: DEV_AVG_SALARY',
    '    type: INPUT',
    '    label: "Средняя ЗП разработчика (net)"',
    '    value: 160000,',
    '    min: 100000,',
    '    max: 300000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: ADMIN_PAYROLL',
    '    type: INTERMEDIATE',
    '    label: "ФОТ административного персонала"',
    '    source: computed',
    '    formula: "ADMIN_HEADCOUNT * ADMIN_AVG_SALARY"',
    '',
    '  - id: ADMIN_HEADCOUNT',
    '    type: INPUT',
    '    label: "Численность АУП (HR, PM, продажи)"',
    '    value: 6,',
    '    min: 2,',
    '    max: 20,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: ADMIN_AVG_SALARY',
    '    type: INPUT',
    '    label: "Средняя ЗП АУП"',
    '    value: 120000,',
    '    min: 80000,',
    '    max: 200000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: MARKETING',
    '    type: INPUT',
    '    label: "Маркетинг и продажи"',
    '    value: 300000,',
    '    min: 100000,',
    '    max: 1000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: RENT',
    '    type: INPUT',
    '    label: "Аренда офиса (или коворкинг)"',
    '    value: 350000,',
    '    min: 100000,',
    '    max: 800000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: IT_EXP',
    '    type: INPUT',
    '    label: "IT-инфраструктура и подписки"',
    '    value: 250000,',
    '    min: 100000,',
    '    max: 800000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: TRAINING_EXP',
    '    type: INPUT',
    '    label: "Обучение и конференции"',
    '    value: 120000,',
    '    min: 50000,',
    '    max: 500000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: FIXED_ASSETS',
    '    type: INPUT',
    '    label: "Основные средства (техника, серверы)"',
    '    value: 4000000,',
    '    min: 1000000,',
    '    max: 15000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: INTANGIBLE_ASSETS',
    '    type: INPUT',
    '    label: "Нематериальные активы (ПО, патенты)"',
    '    value: 2000000,',
    '    min: 0,',
    '    max: 10000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: DA',
    '    type: INTERMEDIATE',
    '    label: "Амортизация"',
    '    source: computed',
    '    formula: "(FIXED_ASSETS + INTANGIBLE_ASSETS) * DA_RATE"',
    '',
    '  - id: DA_RATE',
    '    type: INPUT',
    '    label: "Норма амортизации"',
    '    value: 0.10',
    '    min: 0.05',
    '    max: 0.25',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: LOANS',
    '    type: INPUT',
    '    label: "Кредитный портфель"',
    '    value: 2000000,',
    '    min: 0,',
    '    max: 10000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: LOAN_RATE',
    '    type: INTERMEDIATE',
    '    label: "Средняя ставка по кредитам"',
    '    source: computed',
    '',
    '  - id: CB_RATE',
    '    type: EXTERNAL',
    '    label: "Ключевая ставка ЦБ"',
    '    value: 0.18,',
    '    min: 0.05,',
    '    max: 0.25,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: BANK_SPREAD',
    '    type: INPUT',
    '    label: "Спред банка"',
    '    value: 0.03,',
    '    min: 0.01,',
    '    max: 0.06,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: FCF',
    '    type: INTERMEDIATE',
    '    label: "Свободный денежный поток"',
    '    source: computed',
    '',
    '  - id: CFO',
    '    type: INTERMEDIATE',
    '    label: "Операционный денежный поток"',
    '    source: computed',
    '',
    '  - id: CASH',
    '    type: INTERMEDIATE',
    '    label: "Денежные средства"',
    '    source: computed',
    '    formula: "CASH_START + FCF"',
    '',
    '  - id: CASH_START',
    '    type: INPUT',
    '    label: "Остаток денег на начало"',
    '    value: 5000000,',
    '    min: 0,',
    '    max: 20000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: RECEIVABLES',
    '    type: INPUT',
    '    label: "Дебиторская задолженность"',
    '    value: 3500000,',
    '    min: 0,',
    '    max: 10000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: PAYABLES',
    '    type: INPUT',
    '    label: "Кредиторская задолженность"',
    '    value: 800000,',
    '    min: 0,',
    '    max: 5000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: FX_RATE',
    '    type: EXTERNAL',
    '    label: "Курс USD/RUB"',
    '    value: 95',
    '    min: 70',
    '    max: 130',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: LABOR_INDEX',
    '    type: EXTERNAL',
    '    label: "Индекс рынка труда"',
    '    value: 0.8',
    '    min: 0.5',
    '    max: 1.5',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: SANCTIONS',
    '    type: EXTERNAL',
    '    label: "Санкционный индекс"',
    '    value: 0.7',
    '    min: 0',
    '    max: 1.0',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: GEO_INDEX',
    '    type: EXTERNAL',
    '    label: "Геополитический индекс"',
    '    value: 0.7',
    '    min: 0',
    '    max: 1.0',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: INFLATION',
    '    type: EXTERNAL',
    '    label: "Инфляция"',
    '    value: 0.07',
    '    min: 0.03',
    '    max: 0.20',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: PENALTIES',
    '    type: INPUT',
    '    label: "Штрафы и пени"',
    '    value: 0,',
    '    min: 0,',
    '    max: 2000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: OTHER_INCOME',
    '    type: INPUT',
    '    label: "Прочие доходы (гранты, субсидии)"',
    '    value: 100000,',
    '    min: 0,',
    '    max: 1000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: OTHER_EXP',
    '    type: INPUT',
    '    label: "Прочие расходы"',
    '    value: 150000,',
    '    min: 0,',
    '    max: 500000,',
    '    source: manual',
    '    enabled: true',
    '',
    'edges:',
    '  - from: DEV_PAYROLL',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: IT_EXP',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 0.6',
    '',
    '  - from: TRAINING_EXP',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 0.4',
    '',
    '  - from: TRAINING_EXP',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 0.6',
    '',
    '  - from: ADMIN_PAYROLL',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: RENT',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: IT_EXP',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 0.4',
    '',
    '  - from: MARKETING',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: CB_RATE',
    '    to: LOAN_RATE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: BANK_SPREAD',
    '    to: LOAN_RATE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: REVENUE',
    '    to: EBITDA',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: COGS',
    '    to: EBITDA',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: ADMIN_EXP',
    '    to: EBITDA',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: EBITDA',
    '    to: EBIT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: DA',
    '    to: EBIT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: EBIT',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: INTEREST',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: OTHER_INCOME',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: OTHER_EXP',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: PENALTIES',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: EBT',
    '    to: NET_PROFIT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: TAX',
    '    to: NET_PROFIT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: NET_PROFIT',
    '    to: CFO',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: DA',
    '    to: CFO',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: CFO',
    '    to: FCF',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    'constraints:',
    '  - node: NET_PROFIT',
    '    operator: ">="',
    '    value: 0',
    ''].join('\n');
