var TEMPLATE_RETAIL = [
    'project:',
    '  name: "Торговая компания"',
    '  version: 2',
    '',
    'nodes:',
    '  - id: NET_PROFIT',
    '    type: TARGET',
    '    label: "Чистая прибыль"',
    '    source: computed',
    '',
    '  - id: EBT',
    '    type: INTERMEDIATE',
    '    label: "Прибыль до налогообложения"',
    '    source: computed',
    '',
    '  - id: TAX',
    '    type: INTERMEDIATE',
    '    label: "Налог на прибыль"',
    '    source: computed',
    '    formula: "MAX(0, EBT * TAX_RATE)"',
    '',
    '  - id: TAX_RATE',
    '    type: INPUT',
    '    label: "Ставка налога на прибыль"',
    '    value: 0.20',
    '    min: 0.03',
    '    max: 0.25',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: EBITDA',
    '    type: INTERMEDIATE',
    '    label: "EBITDA"',
    '    source: computed',
    '',
    '  - id: EBIT',
    '    type: INTERMEDIATE',
    '    label: "Операционная прибыль"',
    '    source: computed',
    '',
    '  - id: INTEREST',
    '    type: INTERMEDIATE',
    '    label: "Проценты к уплате"',
    '    source: computed',
    '    formula: "LOANS * LOAN_RATE"',
    '',
    '  - id: GROSS_PROFIT',
    '    type: INTERMEDIATE',
    '    label: "Валовая прибыль"',
    '    source: computed',
    '',
    '  - id: REVENUE',
    '    type: INTERMEDIATE',
    '    label: "Выручка"',
    '    source: computed',
    '    formula: "VOLUME * PRICE"',
    '',
    '  - id: COGS',
    '    type: INTERMEDIATE',
    '    label: "Себестоимость проданных товаров"',
    '    source: computed',
    '',
    '  - id: SELLING_EXP',
    '    type: INTERMEDIATE',
    '    label: "Коммерческие расходы"',
    '    source: computed',
    '',
    '  - id: ADMIN_EXP',
    '    type: INTERMEDIATE',
    '    label: "Управленческие расходы"',
    '    source: computed',
    '',
    '  - id: PRICE',
    '    type: INPUT',
    '    label: "Средний чек"',
    '    value: 3500,',
    '    min: 2000,',
    '    max: 6000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: VOLUME',
    '    type: INPUT',
    '    label: "Количество продаж (ед/мес)"',
    '    value: 4000,',
    '    min: 1000,',
    '    max: 10000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: MARKETING',
    '    type: INPUT',
    '    label: "Маркетинг и реклама"',
    '    value: 500000,',
    '    min: 200000,',
    '    max: 2000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: PURCHASE_COST',
    '    type: INTERMEDIATE',
    '    label: "Закупочная стоимость товаров"',
    '    source: computed',
    '    formula: "VOLUME * UNIT_PURCHASE"',
    '',
    '  - id: UNIT_PURCHASE',
    '    type: INPUT',
    '    label: "Средняя закупочная цена единицы"',
    '    value: 2000,',
    '    min: 1200,',
    '    max: 3500,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: LOGISTICS_COST',
    '    type: INPUT',
    '    label: "Логистика и доставка"',
    '    value: 300000,',
    '    min: 100000,',
    '    max: 800000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: STAFF_PAYROLL',
    '    type: INTERMEDIATE',
    '    label: "ФОТ торгового персонала"',
    '    source: computed',
    '    formula: "STAFF_HEADCOUNT * STAFF_AVG_SALARY"',
    '',
    '  - id: STAFF_HEADCOUNT',
    '    type: INPUT',
    '    label: "Численность продавцов и склада"',
    '    value: 18,',
    '    min: 5,',
    '    max: 50,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: STAFF_AVG_SALARY',
    '    type: INPUT',
    '    label: "Средняя ЗП торгового персонала"',
    '    value: 55000,',
    '    min: 35000,',
    '    max: 80000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: ADMIN_PAYROLL',
    '    type: INTERMEDIATE',
    '    label: "ФОТ административного персонала"',
    '    source: computed',
    '    formula: "ADMIN_HEADCOUNT * ADMIN_AVG_SALARY"',
    '',
    '  - id: ADMIN_HEADCOUNT',
    '    type: INPUT',
    '    label: "Численность АУП"',
    '    value: 8,',
    '    min: 3,',
    '    max: 20,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: ADMIN_AVG_SALARY',
    '    type: INPUT',
    '    label: "Средняя ЗП АУП"',
    '    value: 85000,',
    '    min: 60000,',
    '    max: 120000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: RENT',
    '    type: INPUT',
    '    label: "Аренда торговых и складских помещений"',
    '    value: 700000,',
    '    min: 300000,',
    '    max: 1500000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: IT_EXP',
    '    type: INPUT',
    '    label: "IT-расходы (кассы, учёт, сайт)"',
    '    value: 100000',
    '    min: 30000,',
    '    max: 300000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: FIXED_ASSETS',
    '    type: INPUT',
    '    label: "Основные средства (оборудование, витрины)"',
    '    value: 5000000,',
    '    min: 1000000,',
    '    max: 20000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: DA',
    '    type: INTERMEDIATE',
    '    label: "Амортизация"',
    '    source: computed',
    '    formula: "FIXED_ASSETS * DA_RATE"',
    '',
    '  - id: DA_RATE',
    '    type: INPUT',
    '    label: "Норма амортизации"',
    '    value: 0.10',
    '    min: 0.05',
    '    max: 0.25',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: CAPEX',
    '    type: INPUT',
    '    label: "Капитальные затраты"',
    '    value: 500000,',
    '    min: 0',
    '    max: 5000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: LOANS',
    '    type: INPUT',
    '    label: "Кредитный портфель"',
    '    value: 3000000,',
    '    min: 0',
    '    max: 20000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: LOAN_RATE',
    '    type: INTERMEDIATE',
    '    label: "Средняя ставка по кредитам"',
    '    source: computed',
    '',
    '  - id: CB_RATE',
    '    type: EXTERNAL',
    '    label: "Ключевая ставка ЦБ"',
    '    value: 0.18,',
    '    min: 0.05,',
    '    max: 0.25,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: BANK_SPREAD',
    '    type: INPUT',
    '    label: "Спред банка"',
    '    value: 0.03,',
    '    min: 0.01,',
    '    max: 0.06,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: FCF',
    '    type: INTERMEDIATE',
    '    label: "Свободный денежный поток"',
    '    source: computed',
    '',
    '  - id: CFO',
    '    type: INTERMEDIATE',
    '    label: "Операционный денежный поток"',
    '    source: computed',
    '',
    '  - id: CFI',
    '    type: INTERMEDIATE',
    '    label: "Инвестиционный денежный поток"',
    '    source: computed',
    '',
    '  - id: CFF',
    '    type: INTERMEDIATE',
    '    label: "Финансовый денежный поток"',
    '    source: computed',
    '',
    '  - id: CASH',
    '    type: INTERMEDIATE',
    '    label: "Денежные средства"',
    '    source: computed',
    '    formula: "CASH_START + FCF"',
    '',
    '  - id: CASH_START',
    '    type: INPUT',
    '    label: "Остаток денег на начало"',
    '    value: 2000000,',
    '    min: 0',
    '    max: 10000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: INVENTORY',
    '    type: INPUT',
    '    label: "Товарные запасы"',
    '    value: 6000000,',
    '    min: 2000000,',
    '    max: 15000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: RECEIVABLES',
    '    type: INPUT',
    '    label: "Дебиторская задолженность"',
    '    value: 1500000,',
    '    min: 0',
    '    max: 5000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: PAYABLES',
    '    type: INPUT',
    '    label: "Кредиторская задолженность поставщикам"',
    '    value: 3000000,',
    '    min: 500000,',
    '    max: 10000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: INFLATION',
    '    type: EXTERNAL',
    '    label: "Инфляция"',
    '    value: 0.07',
    '    min: 0.03',
    '    max: 0.20',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: FX_RATE',
    '    type: EXTERNAL',
    '    label: "Курс USD/RUB"',
    '    value: 95',
    '    min: 70',
    '    max: 130',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: CCI',
    '    type: EXTERNAL',
    '    label: "Потребительская уверенность"',
    '    value: -8',
    '    min: -40',
    '    max: 10',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: HOUSEHOLD_INCOME',
    '    type: EXTERNAL',
    '    label: "Доходы населения"',
    '    value: 55000',
    '    min: 30000',
    '    max: 80000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: SANCTIONS',
    '    type: EXTERNAL',
    '    label: "Санкционный индекс"',
    '    value: 0.7',
    '    min: 0',
    '    max: 1.0',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: GEO_INDEX',
    '    type: EXTERNAL',
    '    label: "Геополитический индекс"',
    '    value: 0.7',
    '    min: 0',
    '    max: 1.0',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: LABOR_INDEX',
    '    type: EXTERNAL',
    '    label: "Индекс рынка труда"',
    '    value: 0.8',
    '    min: 0.5',
    '    max: 1.5',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: PENALTIES',
    '    type: INPUT',
    '    label: "Штрафы и пени"',
    '    value: 0,',
    '    min: 0',
    '    max: 3000000,',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: OTHER_INCOME',
    '    type: INPUT',
    '    label: "Прочие доходы"',
    '    value: 50000',
    '    min: 0',
    '    max: 300000',
    '    source: manual',
    '    enabled: true',
    '',
    '  - id: OTHER_EXP',
    '    type: INPUT',
    '    label: "Прочие расходы"',
    '    value: 100000',
    '    min: 0',
    '    max: 300000',
    '    source: manual',
    '    enabled: true',
    '',
    'edges:',
    '  - from: PURCHASE_COST',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: LOGISTICS_COST',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 0.5',
    '',
    '  - from: STAFF_PAYROLL',
    '    to: COGS',
    '    type: LIN',
    '    coefficient: 0.7',
    '',
    '  - from: STAFF_PAYROLL',
    '    to: SELLING_EXP',
    '    type: LIN',
    '    coefficient: 0.3',
    '',
    '  - from: ADMIN_PAYROLL',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: RENT',
    '    to: SELLING_EXP',
    '    type: LIN',
    '    coefficient: 0.6',
    '',
    '  - from: RENT',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 0.4',
    '',
    '  - from: IT_EXP',
    '    to: ADMIN_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: MARKETING',
    '    to: SELLING_EXP',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: CB_RATE',
    '    to: LOAN_RATE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: BANK_SPREAD',
    '    to: LOAN_RATE',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: REVENUE',
    '    to: GROSS_PROFIT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: COGS',
    '    to: GROSS_PROFIT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: GROSS_PROFIT',
    '    to: EBITDA',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: SELLING_EXP',
    '    to: EBITDA',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: ADMIN_EXP',
    '    to: EBITDA',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: EBITDA',
    '    to: EBIT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: DA',
    '    to: EBIT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: EBIT',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: INTEREST',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: OTHER_INCOME',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: OTHER_EXP',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: PENALTIES',
    '    to: EBT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: EBT',
    '    to: NET_PROFIT',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: TAX',
    '    to: NET_PROFIT',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: NET_PROFIT',
    '    to: CFO',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: DA',
    '    to: CFO',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: CAPEX',
    '    to: CFI',
    '    type: LIN',
    '    coefficient: -1.0',
    '',
    '  - from: CASH_START',
    '    to: CASH',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: FCF',
    '    to: CASH',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: CFO',
    '    to: FCF',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: CFI',
    '    to: FCF',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    '  - from: CFF',
    '    to: FCF',
    '    type: LIN',
    '    coefficient: 1.0',
    '',
    'constraints:',
    '  - node: NET_PROFIT',
    '    operator: ">="',
    '    value: 0',
    ''].join('\n');
